//
//  GENERATED by ClosedSource/scripts/prepare_server.rb — never hand-edit.
//
//  The Supabase fat-edge entry: ONE function hosts the whole route table
//  under /functions/v1/dsx/* (full-stack.md T1). Deno-served; the host
//  itself is platform-free.

import { createEdgeHandler, installDataBackend } from "../../../../src/bootloader-deno.ts";
import { installEntities } from "../../../../src/repo.ts";
import { routes } from "../../../../generated/routes.ts";
import { buildInfo } from "../../../../generated/build-info.ts";
import { handlers } from "../../../../generated/handlers.ts";
import { serverConfig } from "../../../../generated/config.ts";
import { backendSetting, dataProviders } from "../../../../generated/providers.ts";
import { installPackages } from "../../../../src/packages.ts";
import { packageModules } from "../../../../generated/packages.ts";
import { entities } from "../../../../generated/entities.ts";
import { mcpTools } from "../../../../generated/mcp-tools.ts";

//  PLATFORM ENV → DECLARED ENV. This wrapper is the Supabase ADAPTER, so mapping Supabase's
//  own variables onto the names the declaration uses belongs here and nowhere else — the host
//  stays platform-free and never learns a vendor's spelling.
//
//  Without this, deploying required setting DSX_DATABASE_URL and DSX_JWT_JWKS_URL as function
//  secrets by hand, which is a CLI step a dashboard-only owner cannot take — and the product
//  thesis is that they never should have to. Supabase injects SUPABASE_DB_URL and SUPABASE_URL
//  into every function already, and the JWKS endpoint is derivable from the second.
//
//  EXPLICIT ALWAYS WINS: a value set on the function overrides the platform default, so the
//  pooler connection string (which serverless wants — SUPABASE_DB_URL is the DIRECT address,
//  and a cold start per request is exactly what the pooler exists for) can still be supplied
//  as DSX_DATABASE_URL without editing anything here.
{
  const g = globalThis as { Deno?: { env?: { get?(k: string): string | undefined; set?(k: string, v: string): void } } };
  const read = (k: string) => g.Deno?.env?.get?.(k);
  //  `Deno.env.set` THROWS on Supabase's edge runtime — its environment is read-only, and the
  //  optional-call `?.` guards an absent method, not a raising one. Unguarded, this mapping
  //  crashed the whole function at boot: every request answered WORKER_ERROR with no diagnostic,
  //  which is strictly worse than the missing-config refusal it was written to prevent.
  //
  //  So the fallback is BEST-EFFORT by construction. Where the platform allows the write it is a
  //  convenience; where it does not, the deploy's own `secrets set` step is the real mechanism
  //  and the boot check still refuses loudly if neither supplied a value. A floor must never be
  //  able to bring down the thing it is propping up.
  const fill = (key: string, value: string | undefined) => {
    if (value === undefined || value === "" || (read(key) ?? "") !== "") return;
    try {
      g.Deno?.env?.set?.(key, value);
    } catch {
      /* read-only environment (Supabase edge): `secrets set` is the supported path there */
    }
  };
  fill("DSX_DATABASE_URL", read("SUPABASE_DB_URL"));
  let base = read("SUPABASE_URL") ?? "";
  while (base.endsWith("/")) base = base.slice(0, -1); // no regex: a Ruby heredoc eats the escape
  fill("DSX_JWT_JWKS_URL", base === "" ? undefined : base + "/auth/v1/.well-known/jwks.json");
}

// The SCHEMA table installs with the function, like the backend below. The Node path
// gets it from generated-loader; a platform wrapper must carry it itself, or every
// declared-CRUD route answers handler_failed naming an undeclared entity (found by
// EXECUTING this wrapper under Deno — reading it never showed the gap).
//  EVERY boot step is inside the guard, not just the last one. An `await` that rejects at module
//  top level kills the isolate before any handler exists, so a failure in the data backend is as
//  invisible as a failure in config resolution: WORKER_ERROR, no cause, on every request.
let handler: (request: Request) => Response | Promise<Response>;
try {
installEntities(entities as unknown as import("../../../../src/repo.ts").EntitySpec[]);

//  DECLARED PACKAGES (Core/Server/Modules/Import) bind at BOOT so a moved export refuses the
//  cold start rather than 500-ing the one route that needed it.
installPackages(packageModules);

// The data backend boots with the FUNCTION, not with a request (plan B5): a cold start
// either has its transport or fails in the platform log where a deploy can see it.
await installDataBackend(
  serverConfig as unknown as import("../../../../src/config.ts").ServerConfig,
  backendSetting,
  dataProviders,
);

//  A boot failure must arrive as a MESSAGE, not as WORKER_ERROR. On a serverless host an
//  exception at module top level kills the isolate before any handler exists, and the platform
//  answers every request with an opaque 500 whose cause is visible only in logs the deployer may
//  not be able to read. That is the same silent-failure shape this codebase refuses everywhere
//  else: assertConfigured already produces a message naming the missing setting, and losing it
//  to an isolate crash wastes the whole diagnostic.
  handler = createEdgeHandler({
    routes: routes as unknown as import("../../../../src/host.ts").ServerRoute[],
    handlers: handlers as never,
    buildInfo,
  }, serverConfig as unknown as import("../../../../src/config.ts").ServerConfig, {
    mcpTools: mcpTools as unknown as import("../../../../src/mcp-face.ts").McpToolRow[],
  });
} catch (e) {
  const detail = e instanceof Error ? `${e.message}${e.stack === undefined ? "" : `
${e.stack}`}` : String(e);
  console.error(`[dsx.server] BOOT FAILED
${detail}`);
  handler = () =>
    new Response(JSON.stringify({ reason: "boot_failed", message: detail }, null, 1), {
      status: 503,
      headers: { "content-type": "application/json; charset=utf-8" },
    });
}

(globalThis as { Deno?: { serve?: (h: unknown) => void } }).Deno?.serve?.(handler);
