//
//  parser-fuzz.test.ts — the SEEDED, DETERMINISTIC hostile-parser fuzz gate (WD-fuzz).
//
//  Contract under test: the two source→IR entry points — parseDsx (the tokenizer/parser,
//  source → XmlNode) and compileComponent (source → the component IR) — must NEVER crash
//  the process on any input. For every case the outcome is EITHER a value (it parsed) OR a
//  throw of the parser's ONE declared structured error type, DsxParseError. Any other thrown
//  type (a RangeError from stack exhaustion, a TypeError from an unguarded access, a bare
//  Error, …) is a FAILURE, as is a single case that blows the per-case time budget (the
//  hang/OOM proxy for a bounded input). A failure prints the seed, family, index and the
//  exact input so it reproduces in one line.
//
//  This replaces a withdrawn README claim ("a 50,000-case run") with a real, committed,
//  repeatable gate. The corpus is generated by a committed mulberry32 PRNG over a FIXED seed
//  set — no Math.random (the runtime forbids it, /web/07, and a fuzz gate must reproduce
//  byte-for-byte). Same seeds ⇒ identical corpus every run. It rides `npm test` (which globs
//  packages/*/test/*.test.ts and is what the codemagic web-kernel lane runs); `npm run fuzz`
//  runs this file alone, and `DSX_FUZZ_CASES=<n> npm run fuzz` runs a larger manual campaign
//  without changing the committed corpus.
//
//  Every hostile byte in the alphabets below is written as an ASCII escape on purpose, so
//  this source file stays pure ASCII and survives grep/git/editor tooling unharmed — the
//  degenerate bytes live in the RUNTIME strings, never in the file bytes.
//

import { test } from "node:test";
import assert from "node:assert/strict";

import { parseDsx, DsxParseError } from "../src/xml.ts";
import { compileComponent } from "../src/component.ts";

// ── seeded PRNG: mulberry32 ───────────────────────────────────────────────────────────
// A 32-bit state, integer-only step + one power-of-two division; fully deterministic and
// identical across platforms (IEEE-754). Chosen over xorshift for its slightly better
// low-bit avalanche at this size.
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function (): number {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

class Rng {
  private nextFloat: () => number;
  constructor(seed: number) {
    this.nextFloat = mulberry32(seed);
  }
  /** the raw [0,1) draw */
  float(): number {
    return this.nextFloat();
  }
  /** integer in [0, nExclusive) */
  int(nExclusive: number): number {
    return Math.floor(this.nextFloat() * nExclusive);
  }
  /** integer in [lo, hi] inclusive */
  range(lo: number, hi: number): number {
    return lo + this.int(hi - lo + 1);
  }
  pick<T>(items: readonly T[]): T {
    return items[this.int(items.length)]!;
  }
  bool(p = 0.5): boolean {
    return this.nextFloat() < p;
  }
  /** repeat a builder 0..maxExclusive-1 times, concatenating */
  repeatStr(maxExclusive: number, build: () => string): string {
    const n = this.int(maxExclusive);
    let out = "";
    for (let i = 0; i < n; i++) out += build();
    return out;
  }
}

// ── the hostile alphabets (ASCII-escaped; the degenerate bytes are runtime-only) ──────
const TAGS: readonly string[] = [
  "stack", "text", "button", "list", "grid", "pager", "image", "scroll", "divider",
  "head", "script", "action", "formula", "variable", "var", "let", "functions",
  "api", "attribute", "event", "watch", "expects", "style", "component", "slot",
  "Card", "Paywall", "NavBar", "x.y", "a.b.c", "on:tap", "1bad", "", "\u81ea\u5b9a\u4e49",
];
const ATTRS: readonly string[] = [
  "value", "class", "style", "on:tap", "on:change", "on:change.throttle", "visible-if",
  "bind", "as", "url", "default", "computed", "payload", "variable", "global", "note",
  "label", "label:ios", "label:web", "hint:android", "data:x", "arg:rate", "id",
  "", "=", "a b", "x\"y", "auto", "ssr", "method",
];
const VALUES: readonly string[] = [
  "1", "0", "true", "false", "a && b", "1 < 2", "{{ x }}", "{{ x", "}} y", "{{{{}}}}",
  "x".repeat(64), "&amp; &lt; &gt; &quot; &apos;", "&#9;&#10;&#13;", "&#999999999999;",
  "&#xFFFFFFFF;", "&#xD800;", "&#0;", "&#11;", "&", "&#", "&#x", "&bogus;", "&amp",
  "'", "\"", "<script>", "score < 10", "/api/orders", "orders.-1", "a".repeat(200),
];
// NUL, VT, FF, US, BEL, the U+FFFE/U+FFFF non-characters, a lone HIGH and a lone LOW
// surrogate, a valid astral pair (emoji), BOM, zero-width space, the last pre-surrogate
// scalar (U+D7FF), and ordinary whitespace — every XML-character contract, both sides.
const HOSTILE: readonly string[] = [
  "\u0000", "\u0007", "\u000B", "\u000C", "\u001F", "\uFFFE", "\uFFFF",
  "\uD800", "\uDC00", "\uD83D\uDE00", "\uFEFF", "\u200B", "\uD7FF", " ", "\t", "\r", "\n",
];
const FRAGMENTS: readonly string[] = [
  "<", ">", "</", "/>", "<!--", "-->", "<![CDATA[", "]]>", "<?", "?>", "=", "\"", "'",
  "&", "{{", "}}", "{", "}", "(", ")", "[", "]", "\\", "://", ": ", "<a", "<a>", "</a>",
  "< a", "<a/", "<a b", "<a b=", "<a b=\"", "<a b='", "&#;", "&#x;", "&amp", "<a>&#",
];
// Valid-ish head blocks — a mix of well-formed and malformed declarations. The <api>
// rows deliberately include the identifier-rejecting forms (the hardened error path).
const HEAD_BLOCKS: readonly string[] = [
  `<attribute as="title" default="'x'"/>`, `<attribute as=""/>`, `<attribute/>`,
  `<api as="orders" url="/x"/>`, `<api as="orders_2" url="/x"/>`, `<api as="a.b" url="/x"/>`,
  `<api url="/x"/>`, `<api as="ok"/>`, `<api as="${"z".repeat(200)}" url="/x"/>`,
  `<variable as="v">return 1</variable>`, `<variable as="">x</variable>`,
  `<let as="c" computed="true">a + b</let>`, `<formula as="f" x="1">return x</formula>`,
  `<action as="go" arg="1">doThing()</action>`, `<event as="tap" payload="a b c"/>`,
  `<event/>`, `<watch value="x" on:change="f()" on:change.throttle="80"/>`,
  `<watch value="x" on:change.throttle="not-a-number"/>`, `<watch/>`,
  `<script>function a(){ return 1 < 2 && 'a</b>' }</script>`,
  `<functions global="true">function g(){}</functions>`, `<functions global>function g(){}</functions>`,
  `<style>.x{color:red}</style>`, `<component/>`, `<mystery attr="1"/>`,
];
// Actually-valid skeletons — the seed ground for the byte-mutation family, so mutations
// start from parseable input and reach deep code with small perturbations.
const VALID_SKELETONS: readonly string[] = [
  `<stack><text value="hi"/></stack>`,
  `<stack><head><variable as="x">return 1</variable></head><text value="{{ x }}"/></stack>`,
  `<stack><head><api as="orders" url="/api/orders"/></head><list bind="orders"/></stack>`,
  `<stack note="1 &lt; 2"><button on:tap="go()"><text value="A &amp; B"/></button></stack>`,
  `<stack><head><functions global="true">function g(n){return n*2}</functions></head><Card title="Hi"/></stack>`,
  `<text><![CDATA[ raw <b> & stuff ]]></text>`,
  `<!-- lead --><stack><divider/><text>plain</text></stack>`,
];
const INJECT: readonly string[] = [
  "<", ">", "\"", "'", "&", "&#", "&#x", "{{", "}}", "\u0000", "\uD800", "\uDC00", "\uFFFE",
  "\u000C", "/>", "</", "=", "&#999999999999;", "\t", "\n", "  ", "://", "\\", "]]>", "-->",
  "<![CDATA[", "<!--", "<?", "<head>", "</head>", `<api as=".">`, " global",
];

// ── generator families ────────────────────────────────────────────────────────────────
// Each takes an Rng and returns one hostile/degenerate .dsx string. Sizes are bounded so
// the whole gate stays inside the CI time budget below.

function genTokenSalad(rng: Rng): string {
  const n = rng.range(1, 120);
  let out = "";
  for (let i = 0; i < n; i++) {
    const r = rng.float();
    if (r < 0.24) out += "<" + rng.pick(TAGS);
    else if (r < 0.40) out += " " + rng.pick(ATTRS) + "=\"" + rng.pick(VALUES) + "\"";
    else if (r < 0.52) out += ">";
    else if (r < 0.62) out += "</" + rng.pick(TAGS) + ">";
    else if (r < 0.72) out += "/>";
    else if (r < 0.82) out += rng.pick(VALUES);
    else if (r < 0.90) out += rng.pick(HOSTILE);
    else out += rng.pick(FRAGMENTS);
  }
  return out;
}

function genDeepNesting(rng: Rng): string {
  // straddle DSX_PARSE_LIMITS.maxDepth (256): sometimes under, often over.
  const depth = rng.range(1, 400);
  const tag = rng.pick(["a", "stack", "b", "x.y"]);
  let s = "";
  for (let i = 0; i < depth; i++) s += "<" + tag + (rng.bool(0.15) ? " k=\"" + rng.pick(VALUES) + "\"" : "") + ">";
  s += rng.pick(VALUES);
  const mode = rng.int(4);
  const closes = mode === 0 ? depth : mode === 1 ? rng.range(0, depth) : mode === 2 ? depth + rng.range(1, 5) : depth;
  const closeTag = mode === 3 ? rng.pick(["c", "wrong", tag]) : tag;
  for (let i = 0; i < closes; i++) s += "</" + closeTag + ">";
  return s;
}

function genAttributeStorm(rng: Rng): string {
  const n = rng.range(1, 400);
  let s = "<" + rng.pick(["a", "stack", "input", "api"]);
  for (let i = 0; i < n; i++) {
    s += " " + rng.pick(ATTRS);
    if (rng.bool(0.75)) {
      const open = rng.pick(["\"", "'", ""]);
      const close = rng.bool(0.8) ? open : rng.pick(["\"", "'", ""]);
      s += "=" + open + rng.pick(VALUES) + close;
    }
  }
  s += rng.bool() ? ">" : "/>";
  if (rng.bool(0.5)) s += "</a>";
  return s;
}

function genEntityStorm(rng: Rng): string {
  const token = rng.pick([
    "&", "&#", "&#x", "&amp;", "&#9;", "&lt;", "&#999999999999;", "&#xFFFFFF;",
    "&#xD800;", "&bogus;", "{{", "}}", "&#0;", "&#x;",
  ]);
  const n = rng.range(1, 3000);
  const flood = token.repeat(n);
  const where = rng.int(3);
  if (where === 0) return "<a>" + flood + "</a>";
  if (where === 1) return `<a note="` + flood + `"/>`;
  return "<a note=\"" + token.repeat(rng.range(1, 200)) + "\">" + flood + "</a>";
}

function genCodeTagBodies(rng: Rng): string {
  const tag = rng.pick(["script", "variable", "action", "formula", "functions", "let", "var"]);
  const body = rng.repeatStr(24, () =>
    rng.pick(["1 < 2", "a</b>", "for(;;){}", "{{{{", "}}}}", "'\"`", "&& || >>", "</" + tag + " ", ""]),
  );
  const closeMode = rng.int(3);
  const close = closeMode === 0 ? "</" + tag + ">" : closeMode === 1 ? "" : rng.pick(["</wrong>", "</" + tag, "< /" + tag + ">"]);
  const wrapped = "<" + tag + " as=\"x\">" + body + close;
  return rng.bool(0.6) ? "<stack><head>" + wrapped + "</head></stack>" : wrapped;
}

function genHostileBytes(rng: Rng): string {
  const byte = (): string => rng.pick(HOSTILE);
  const context = rng.int(6);
  if (context === 0) return `<a note="` + rng.repeatStr(40, byte) + `"/>`;
  if (context === 1) return "<a>" + rng.repeatStr(60, byte) + "</a>";
  if (context === 2) return "<a><!--" + rng.repeatStr(40, byte) + "--></a>";
  if (context === 3) return "<a><![CDATA[" + rng.repeatStr(40, byte) + "]]></a>";
  if (context === 4) return "<" + rng.repeatStr(20, byte) + "a>x</a>";
  return rng.repeatStr(80, () => (rng.bool(0.5) ? byte() : rng.pick(FRAGMENTS)));
}

function genHeadDocument(rng: Rng): string {
  const head = rng.repeatStr(6, () => rng.pick(HEAD_BLOCKS));
  const body = rng.repeatStr(4, () =>
    rng.pick([
      `<text value="{{ v }}"/>`, `<stack><text value="a"/></stack>`, `<Card title="hi"/>`,
      `<x.y a="1"/>`, `<button on:tap="go()"/>`, `<list bind="items"/>`, `<text>plain</text>`,
    ]),
  );
  const openHead = rng.bool(0.9) ? "<head>" : rng.pick(["<head>", "<head ", "<HEAD>", ""]);
  const closeHead = rng.bool(0.9) ? "</head>" : rng.pick(["", "</head", "</Head>"]);
  const rootTag = rng.pick(["stack", "view", "a"]);
  return `<${rootTag}>` + openHead + head + closeHead + body + `</${rootTag}>`;
}

function genMutatedValid(rng: Rng): string {
  let out = rng.pick(VALID_SKELETONS);
  const rounds = rng.range(1, 8);
  for (let r = 0; r < rounds; r++) {
    const op = rng.int(4);
    if (op === 0) {
      const pos = rng.int(out.length + 1);
      out = out.slice(0, pos) + rng.pick(INJECT) + out.slice(pos);
    } else if (op === 1 && out.length > 0) {
      const pos = rng.int(out.length);
      out = out.slice(0, pos) + out.slice(pos + 1);
    } else if (op === 2 && out.length > 0) {
      const pos = rng.int(out.length);
      out = out.slice(0, pos) + rng.pick(INJECT) + out.slice(pos + 1);
    } else {
      const pos = rng.int(out.length + 1);
      out = out.slice(0, pos) + rng.pick(INJECT).repeat(rng.range(1, 400)) + out.slice(pos);
    }
  }
  return out;
}

type Family = { readonly name: string; readonly gen: (rng: Rng) => string };
const FAMILIES: readonly Family[] = [
  { name: "tokenSalad", gen: genTokenSalad },
  { name: "deepNesting", gen: genDeepNesting },
  { name: "attributeStorm", gen: genAttributeStorm },
  { name: "entityStorm", gen: genEntityStorm },
  { name: "codeTagBodies", gen: genCodeTagBodies },
  { name: "hostileBytes", gen: genHostileBytes },
  { name: "headDocument", gen: genHeadDocument },
  { name: "mutatedValid", gen: genMutatedValid },
];

// ── the campaign shape (N) ────────────────────────────────────────────────────────────
// The FIXED seed set — a fixed set ⇒ an identical corpus on every run (reproducibility is
// the whole point). Twelve seeds, each seeding an independent generator stream.
const FUZZ_SEEDS: readonly number[] = [
  0x00000001, 0x9e3779b9, 0x6d2b79f5, 0xc2b2ae35, 0x27d4eb2f, 0x165667b1,
  0x85ebca77, 0xd3a2646c, 0xfd7046c5, 0xb55a4f09, 0xdeadbeef, 0xc0ffee11,
];
// N (documents) = FUZZ_SEEDS.length × CASES_PER_SEED = 12 × 640 = 7,680 generated .dsx
// documents, each driven through BOTH entry points ⇒ 15,360 parse/compile invocations.
// CASES_PER_SEED is a build-time constant sized so the gate adds ≈1.5s to `npm test` on CI
// hardware (measured ≈1.4s; the parser's own byte/node/depth bounds guarantee every case
// terminates). For a deeper manual sweep, `DSX_FUZZ_CASES=<n> npm run fuzz` overrides the
// per-seed count WITHOUT touching the committed corpus — unset ⇒ the constant below, so CI
// is always deterministic.
const CASES_PER_SEED = 640;
const casesPerSeed = ((): number => {
  const override = Number(process.env["DSX_FUZZ_CASES"]);
  return Number.isInteger(override) && override > 0 ? override : CASES_PER_SEED;
})();

// A single bounded hostile input must parse or reject far under this; exceeding it is
// treated as a hang / OOM-class failure (the parser bounds documents to 4 MiB / 50k nodes
// / 256 levels, so real inputs finish in single-digit ms).
const PER_CASE_BUDGET_MS = 2000;

type Finding = {
  readonly entry: string;
  readonly seed: number;
  readonly family: string;
  readonly index: number;
  readonly detail: string;
  readonly input: string;
};

function reproLine(f: Finding): string {
  const escaped = JSON.stringify(f.input);
  // Point the reproduce command at the ENTRY POINT that actually failed, so pasting it
  // re-triggers the exact throw (compileComponent-only failures don't repro via parseDsx).
  const call = f.entry === "compileComponent"
    ? `import("./packages/compiler/src/component.ts").then(m=>m.compileComponent("Fuzz","fuzz",${escaped}))`
    : `import("./packages/compiler/src/xml.ts").then(m=>m.parseDsx(${escaped}))`;
  return [
    `\n  FUZZ FAILURE — the ${f.entry} path did not honor the parse-or-DsxParseError contract.`,
    `  seed=0x${(f.seed >>> 0).toString(16)} family=${f.family} index=${f.index}`,
    `  detail: ${f.detail}`,
    `  input (${f.input.length} chars): ${escaped.length > 400 ? escaped.slice(0, 400) + "…" : escaped}`,
    `  reproduce (from OpenSource/Web): node -e '${call}'`,
  ].join("\n");
}

/** Run one entry point on one case; record a Finding unless it returned or threw DsxParseError. */
function exercise(
  entry: string,
  run: () => unknown,
  seed: number,
  family: string,
  index: number,
  input: string,
  findings: Finding[],
): void {
  const started = performance.now();
  try {
    run();
  } catch (e) {
    if (!(e instanceof DsxParseError)) {
      const detail = e instanceof Error ? `${e.constructor.name}: ${e.message}` : `non-Error throw: ${String(e)}`;
      findings.push({ entry, seed, family, index, detail, input });
      return;
    }
  }
  const elapsed = performance.now() - started;
  if (elapsed > PER_CASE_BUDGET_MS) {
    findings.push({ entry, seed, family, index, detail: `${elapsed.toFixed(0)}ms > ${PER_CASE_BUDGET_MS}ms budget (hang/OOM class)`, input });
  }
}

// ── determinism gates ─────────────────────────────────────────────────────────────────

test("parser fuzz: mulberry32 PRNG matches its committed reference vectors (no Math.random)", () => {
  // `float() * 2**32` recovers the raw u32 exactly (2**32 is a power of two), so these
  // integer vectors pin the generator with zero float-formatting ambiguity.
  const one = new Rng(1);
  assert.deepEqual(
    [one.float(), one.float(), one.float(), one.float()].map((x) => Math.round(x * 4294967296)),
    [2693262067, 11749833, 2265367787, 4213581821],
  );
  const coffee = new Rng(0xc0ffee);
  assert.deepEqual(
    [coffee.float(), coffee.float(), coffee.float()].map((x) => Math.round(x * 4294967296)),
    [90802087, 2860920651, 3349951739],
  );
  // every draw is in [0, 1)
  const r = new Rng(42);
  for (let i = 0; i < 5000; i++) {
    const v = r.float();
    assert.ok(v >= 0 && v < 1, `draw out of range: ${v}`);
  }
});

test("parser fuzz: the fixed seed set produces a byte-identical corpus every run", () => {
  const build = (): string[] => {
    const corpus: string[] = [];
    for (const seed of FUZZ_SEEDS) {
      const rng = new Rng(seed);
      for (let i = 0; i < 96; i++) {
        const family = FAMILIES[rng.int(FAMILIES.length)]!;
        corpus.push(family.name + " " + family.gen(rng));
      }
    }
    return corpus;
  };
  assert.deepEqual(build(), build(), "regenerating the corpus from the same seeds must be identical");
});

// ── the gate ──────────────────────────────────────────────────────────────────────────

test("parser fuzz: seeded hostile documents parse or raise DsxParseError — never crash the process", () => {
  const findings: Finding[] = [];
  let documents = 0;
  const perFamily: Record<string, number> = {};
  const startedAll = performance.now();

  for (const seed of FUZZ_SEEDS) {
    const rng = new Rng(seed);
    for (let index = 0; index < casesPerSeed; index++) {
      const family = FAMILIES[rng.int(FAMILIES.length)]!;
      const input = family.gen(rng);
      documents += 1;
      perFamily[family.name] = (perFamily[family.name] ?? 0) + 1;
      exercise("parseDsx", () => parseDsx(input), seed, family.name, index, input, findings);
      exercise("compileComponent", () => compileComponent("Fuzz", "fuzz", input), seed, family.name, index, input, findings);
      // stop early on the first failure so the reproduction is the first offender, not the last
      if (findings.length > 0) break;
    }
    if (findings.length > 0) break;
  }

  const elapsed = performance.now() - startedAll;
  if (findings.length > 0) {
    assert.fail(reproLine(findings[0]!));
  }
  // sanity: the campaign actually ran the committed number of documents and touched every family
  assert.equal(documents, FUZZ_SEEDS.length * casesPerSeed, "campaign document count drifted from the constant");
  for (const family of FAMILIES) {
    assert.ok((perFamily[family.name] ?? 0) > 0, `family ${family.name} generated no cases`);
  }
  // guard the CI budget so a future superlinear regression is caught here, not in a red lane.
  // Only the committed default N carries the fixed aggregate ceiling; a deliberate
  // DSX_FUZZ_CASES deep run is bounded by the per-case budget above instead.
  if (casesPerSeed === CASES_PER_SEED) {
    assert.ok(elapsed < 20_000, `fuzz campaign exceeded its CI time budget: ${elapsed.toFixed(0)}ms`);
  }
});

// ── the hardening this gate landed (mutation-proven regression) ───────────────────────

test("parser fuzz: <api as> validation raises the structured DsxParseError, not a bare Error", () => {
  // WD-fuzz found the ONE non-DsxParseError leak across the whole source→IR path here:
  // compileComponent's <api as> head validation threw a bare Error. It now raises the
  // declared structured type, so a caller catching DsxParseError sees every malformed
  // .dsx uniformly. These exact inputs are what the seeded corpus surfaced.
  for (const bad of [
    `<stack><head><api as="orders.-1" url="/x"/></head></stack>`,
    `<stack><head><api url="/x"/></head></stack>`,
    `<stack><head><api as="" url="/x"/></head></stack>`,
    `<stack><head><api as="${"z".repeat(129)}" url="/x"/></head></stack>`,
  ]) {
    assert.throws(
      () => compileComponent("Api", "test", bad),
      (error: unknown) => error instanceof DsxParseError && /ASCII identifier/.test((error as DsxParseError).message),
      `expected a DsxParseError for: ${bad}`,
    );
  }
  // a valid <api as> still compiles
  const ok = compileComponent("Api", "test", `<stack><head><api as="orders_2" url="/x"/></head></stack>`);
  assert.deepEqual(ok.head.apis.map((a) => a.as), ["orders_2"]);
});
