//
//  registry-commands.ts — `despia search · add · remove · list`, over registry.ts (coordinates,
//  lockfile) and registry-resolve.ts (git, hash, cache).
//
//  THE FIRST-PARTY INDEX IS BUNDLED, generated from the capability manifest at build time and
//  shipped next to this file, so `despia search camera` answers offline, on the first run, before
//  the user has heard of the registry. `--remote` adds the community index; resolution never
//  reads either.
//
//  BOTH TIERS INSTALL WITHOUT A GATE. A module's `tier` decides one line of output, not
//  whether the command works: a premium module installs exactly like an open one and prints
//  what the watermark costs to remove. Try-everything-free is the funnel; the gate lives at
//  ship time, not here.
//

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { CONFIG_FILENAME, findProjectRoot, loadConfig } from "./config.ts";
import {
  RegistryError, emptyLockfile, lockAdd, lockRemove, parsePackageRef, refId,
  searchIndex, serializeLockfile,
  type LockEntry, type Lockfile, type RegistryIndex,
} from "./registry.ts";
import {
  ResolveError, defaultCacheDir, isOffline, materialize, resolveGitPackage,
  type ResolvedPackage,
} from "./registry-resolve.ts";
import { manifestGrants, readAppManifest } from "./studio-apps/manifest.ts";

type Io = { out: (line: string) => void; err: (line: string) => void };
type Flags = { [name: string]: string | boolean };

export const LOCK_FILENAME = "dsx.lock.json";
const COMMUNITY_INDEX_URL = "https://despia-native.github.io/registry/index.json";
const PRICING_URL = "https://despia.com/pricing";

// ── the lockfile on disk ────────────────────────────────────────────────────────────────

export function readLockfile(root: string): Lockfile {
  const path = join(root, LOCK_FILENAME);
  if (!existsSync(path)) return emptyLockfile();
  let doc: unknown;
  try { doc = JSON.parse(readFileSync(path, "utf8")); } catch (e) {
    throw new RegistryError(`${LOCK_FILENAME} is not valid JSON: ${e instanceof Error ? e.message : String(e)}`);
  }
  const lock = doc as Lockfile;
  if (lock.version !== 1 || typeof lock.modules !== "object" || lock.modules === null) {
    throw new RegistryError(`${LOCK_FILENAME} is not a v1 lockfile — expected { "version": 1, "modules": { … } }`);
  }
  return lock;
}

export function writeLockfile(root: string, lock: Lockfile): void {
  writeFileSync(join(root, LOCK_FILENAME), serializeLockfile(lock));
}

/** The project the registry commands act on. Registry state is per-project by design (Q6):
 *  the lockfile lives next to dsx.config.json, never in the framework repo. */
export function requireProjectRoot(flags: Flags): { root: string; scheme: string } {
  const cwd = process.cwd();
  const explicit = typeof flags["project"] === "string" ? resolve(cwd, flags["project"]) : null;
  const root = explicit ?? findProjectRoot(cwd);
  if (root === null) {
    throw new RegistryError(
      `no ${CONFIG_FILENAME} found in ${cwd} or any parent — packages are added to a project. ` +
      "Scaffold one with `npm create despia`, or pass --project <dir>.",
    );
  }
  return { root, scheme: loadConfig(root).scheme };
}

// ── the bundled first-party index ───────────────────────────────────────────────────────

/** Generated by ClosedSource/scripts/generate_first_party_index.rb — regenerate, never edit. */
export function firstPartyIndex(): RegistryIndex {
  const path = join(dirname(fileURLToPath(import.meta.url)), "first-party-index.json");
  return JSON.parse(readFileSync(path, "utf8")) as RegistryIndex;
}

// ── search ──────────────────────────────────────────────────────────────────────────────

export async function commandSearch(flags: Flags, positional: string[], io: Io): Promise<number> {
  const query = positional[0];
  if (query === undefined || query.trim() === "") {
    throw new RegistryError("what should I search for? — despia search camera");
  }
  const index = firstPartyIndex();
  const merged: RegistryIndex = { ...index, packages: [...index.packages] };

  if (flags["remote"] === true || typeof flags["index"] === "string") {
    const from = typeof flags["index"] === "string" ? flags["index"] : COMMUNITY_INDEX_URL;
    merged.packages.push(...(await communityIndex(from)).packages);
  }

  const hits = searchIndex(merged, query.trim());
  if (hits.length === 0) {
    io.out(`no matches for ${JSON.stringify(query)} in ${merged.packages.length} package(s)` +
      (flags["remote"] !== true && typeof flags["index"] !== "string" ? " — add --remote to search the community index" : ""));
    return 0;
  }
  for (const hit of hits) {
    const where = hit.repo !== undefined ? `despia add ${hit.id}` : "ships with the framework";
    io.out(`${hit.scheme.padEnd(16)} ${hit.name.padEnd(20)} ${hit.version.padEnd(9)} ${where}` +
      (hit.summary !== "" ? `  — ${hit.summary}` : ""));
  }
  return 0;
}

async function communityIndex(from: string): Promise<RegistryIndex> {
  if (/^https?:\/\//.test(from)) {
    if (isOffline()) throw new RegistryError("DSX_OFFLINE is set and --remote needs the network");
    const response = await fetch(from);
    if (!response.ok) throw new RegistryError(`the community index at ${from} answered ${response.status}`);
    return await response.json() as RegistryIndex;
  }
  const path = resolve(from);
  if (!existsSync(path)) throw new RegistryError(`no index at ${path}`);
  return JSON.parse(readFileSync(path, "utf8")) as RegistryIndex;
}

// ── add ─────────────────────────────────────────────────────────────────────────────────

export interface AddOptions {
  /** Test seam: remote per package id, overriding the GitHub URL derived from the ref. */
  remotes?: { [id: string]: string };
  cacheDir?: string;
  ledger?: { [id: string]: { [version: string]: string } };
}

export async function commandAdd(flags: Flags, positional: string[], io: Io, opts: AddOptions = {}): Promise<number> {
  const raw = positional[0];
  if (raw === undefined) throw new RegistryError("what should I add? — despia add github:owner/repo@1.2.0");
  const ref = parsePackageRef(raw);

  if (ref.kind === "first-party") {
    const id = refId(ref);
    const known = firstPartyIndex().packages.find((p) => p.id === id || p.scheme === id);
    if (known === undefined) {
      // A path that names no first-party module was most likely a bare owner/repo — the one
      // ambiguity resolution refuses to guess at. Refuse with the correction, never a fetch.
      io.err(`despia add: ${JSON.stringify(ref.path)} is not a first-party module this CLI knows.`);
      io.err("If you meant a GitHub repository, name the host — that spelling is never guessed:");
      io.err(`  despia add github:${ref.path}`);
      return 1;
    }
    // The defined refusal, not a mystery (plan §6 W3): while the first-party modules ship only
    // inside the framework and Despia Cloud builds, this coordinate has nothing public to
    // resolve. The moment the module is mirrored, the SAME command starts working, no CLI change.
    io.err(`despia add: ${known.id} is a first-party Despia module. First-party modules ship with the`);
    io.err("framework and Despia Cloud builds today — they are not yet published as standalone");
    io.err(`repositories, so there is nothing for this command to fetch. Docs and the full API:`);
    io.err(`  https://despia.com/packages/${known.id}`);
    return 1;
  }

  const project = requireProjectRoot(flags);
  const lock = readLockfile(project.root);
  const cacheDir = opts.cacheDir ?? defaultCacheDir();

  // Resolve the root package first — its manifest names its dependencies, so the full plan is
  // printable only after this one fetch. Nothing is PINNED until the whole plan verified.
  const root = resolveGitPackage(ref, lock.modules[refId(ref)] ?? null, {
    cacheDir,
    ...(opts.remotes?.[refId(ref)] !== undefined ? { remote: opts.remotes[refId(ref)]! } : {}),
    ledger: opts.ledger?.[refId(ref)] ?? null,
  });

  const plan: ResolvedPackage[] = [root];
  if (flags["no-deps"] !== true) {
    collectDependencies(root, plan, lock, cacheDir, opts);
  } else if (requiresOf(root.manifest).length > 0) {
    io.out(`[despia add] --no-deps: ${root.id} declares ${requiresOf(root.manifest).length} dependenc(ies) you are wiring by hand`);
  }

  refuseSchemeCollisions(plan, lock, project);

  for (const pkg of plan) {
    io.out(`[despia add] will pin ${pkg.id} ${pkg.version} (${pkg.sha256.slice(0, 19)}… commit ${pkg.resolved.slice(0, 12)})` +
      (pkg.crossChecked ? "" : "  [trust-on-first-use: no ledger entry]"));
  }
  if (flags["dry-run"] === true) {
    io.out("[despia add] dry run — nothing written");
    return 0;
  }

  let next = lock;
  for (const pkg of plan) {
    const scheme = typeof pkg.manifest["scheme"] === "string" ? pkg.manifest["scheme"] : "";
    const entry: LockEntry = {
      version: pkg.version,
      source: pkg.id,
      resolved: pkg.resolved,
      sha256: pkg.sha256,
      ...(scheme !== "" ? { scheme } : {}),
      crossChecked: pkg.crossChecked,
    };
    next = lockAdd(next, pkg.id, entry);
  }
  writeLockfile(project.root, next);
  io.out(`[despia add] pinned ${plan.length} package(s) → ${LOCK_FILENAME}`);

  for (const pkg of plan) {
    if (pkg.manifest["tier"] === "premium") {
      // The whole commercial gate, stated at the moment of install and never enforced here:
      io.out(`[despia add] ${pkg.id} is a premium module — free to use with the Despia watermark; ` +
        `$249 per app/OS removes it: ${PRICING_URL}`);
    }
    // A Studio app's grants, said at the moment of install (studio-apps.md §6). Saying is
    // all this does: an installed app stays DISABLED until a person enables it in the
    // Studio's Apps panel, and the scoped seam refuses ungrated calls either way.
    const asApp = readAppManifest(pkg.manifest);
    if (asApp.info !== null) {
      const grants = manifestGrants(asApp.info);
      io.out(`[despia add] ${pkg.id} is a Despia app (${asApp.info.contributions.length} contribution(s)). It asks for:`);
      if (grants.length === 0) io.out("[despia add]   no permissions");
      for (const grant of grants) io.out(`[despia add]   ${grant}`);
      io.out("[despia add] it stays disabled until you enable it in the Studio's Apps panel (despia edit → Apps)");
      const approvalPath = join(project.root, ".despia", "apps", "approvals", `${asApp.info.scheme}.json`);
      if (!existsSync(approvalPath)) {
        io.out(`[despia add] no shelf approval on file — an installed app mounts and runs only once ` +
          `${relative(project.root, approvalPath)} carries the shelf's signed approval for this exact tree ` +
          "(studio-apps.md §11; `despia app verify` checks the chain)");
      }
    }
  }
  return 0;
}

/** `requires` in a package manifest: registry coordinates at exact versions. (`dependencies`
 *  already means native binary coordinates in first-party manifests, so the registry uses its
 *  own word rather than overloading one that resolves through SPM/Gradle.) */
function requiresOf(manifest: { [k: string]: unknown }): Array<{ id: string; version: string }> {
  const block = manifest["requires"];
  if (block === null || typeof block !== "object" || Array.isArray(block)) return [];
  const out: Array<{ id: string; version: string }> = [];
  for (const [id, version] of Object.entries(block as { [k: string]: unknown })) {
    if (typeof version !== "string") throw new ResolveError(`requires[${JSON.stringify(id)}] must be an exact version string`);
    out.push({ id, version });
  }
  return out;
}

function collectDependencies(
  from: ResolvedPackage, plan: ResolvedPackage[], lock: Lockfile, cacheDir: string, opts: AddOptions,
): void {
  for (const dep of requiresOf(from.manifest)) {
    if (dep.version === "") {
      throw new ResolveError(`${from.id} requires ${dep.id} with no version — v1 has no ranges and no solver, a requirement is an exact pin`);
    }
    const depRef = parsePackageRef(`${dep.id}@${dep.version}`);
    if (depRef.kind !== "git") {
      throw new ResolveError(
        `${from.id} requires ${JSON.stringify(dep.id)}, which is not a registry coordinate — ` +
        "a package's dependencies live in the same github: space it does",
      );
    }
    const depId = refId(depRef);
    const planned = plan.find((p) => p.id === depId);
    if (planned !== undefined) {
      if (planned.version !== dep.version) {
        throw new ResolveError(
          `version conflict: ${from.id} requires ${depId}@${dep.version} but ${planned.version} ` +
          "is already in this plan — two packages demanding different pins is a refusal, never a silent winner",
        );
      }
      continue;
    }
    const locked = lock.modules[depId];
    if (locked !== undefined && locked.version !== dep.version) {
      throw new ResolveError(
        `version conflict: ${from.id} requires ${depId}@${dep.version} but the lockfile pins ` +
        `${locked.version} — remove the existing pin first if the bump is intended`,
      );
    }
    const resolved = resolveGitPackage(depRef, locked ?? null, {
      cacheDir,
      ...(opts.remotes?.[depId] !== undefined ? { remote: opts.remotes[depId]! } : {}),
      ledger: opts.ledger?.[depId] ?? null,
    });
    plan.push(resolved);
    collectDependencies(resolved, plan, lock, cacheDir, opts);
  }
}

/** A scheme the project already routes cannot be claimed twice: the collision would otherwise
 *  surface as a duplicate-chain abort at prepare time, far from the command that caused it. */
function refuseSchemeCollisions(
  plan: ResolvedPackage[], lock: Lockfile, project: { root: string; scheme: string },
): void {
  const taken = new Map<string, string>();
  taken.set(project.scheme.toLowerCase(), "this project");
  for (const [id, entry] of Object.entries(lock.modules)) {
    if (entry.scheme !== undefined) taken.set(entry.scheme.toLowerCase(), id);
  }
  const modulesDir = join(project.root, "Modules");
  if (existsSync(modulesDir)) {
    for (const name of readdirSync(modulesDir).sort()) {
      const manifestPath = join(modulesDir, name, "dsx.json");
      if (!statSync(join(modulesDir, name)).isDirectory() || !existsSync(manifestPath)) continue;
      try {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as { scheme?: unknown };
        if (typeof manifest.scheme === "string" && manifest.scheme !== "") {
          taken.set(manifest.scheme.toLowerCase(), `Modules/${name}`);
        }
      } catch { /* an unparseable local module is export's problem, not add's */ }
    }
  }
  for (const pkg of plan) {
    const scheme = typeof pkg.manifest["scheme"] === "string" ? pkg.manifest["scheme"].toLowerCase() : "";
    if (scheme === "") continue;
    const owner = taken.get(scheme);
    if (owner !== undefined && owner !== pkg.id) {
      throw new ResolveError(
        `scheme collision: ${pkg.id} fronts "${scheme}", which ${owner} already provides in this ` +
        "project — two providers of one scheme is a duplicate chain at prepare time",
      );
    }
    taken.set(scheme, pkg.id);
  }
}

// ── remove ──────────────────────────────────────────────────────────────────────────────

export function commandRemove(flags: Flags, positional: string[], io: Io): number {
  const raw = positional[0];
  if (raw === undefined) throw new RegistryError("what should I remove? — despia remove github:owner/repo");
  const id = refId(parsePackageRef(raw));
  const project = requireProjectRoot(flags);
  const lock = readLockfile(project.root);
  if (lock.modules[id] === undefined) {
    const have = Object.keys(lock.modules);
    throw new RegistryError(`${id} is not pinned` +
      (have.length > 0 ? ` — this project pins: ${have.join(", ")}` : ` — ${LOCK_FILENAME} is empty`));
  }
  if (flags["dry-run"] === true) {
    io.out(`[despia remove] would unpin ${id} ${lock.modules[id]!.version} — dry run, nothing written`);
    return 0;
  }
  writeLockfile(project.root, lockRemove(lock, id));
  io.out(`[despia remove] unpinned ${id} — the cache keeps the bytes; re-adding is offline`);
  return 0;
}

// ── list ────────────────────────────────────────────────────────────────────────────────

export function commandList(flags: Flags, _positional: string[], io: Io, cacheDir = defaultCacheDir()): number {
  const project = requireProjectRoot(flags);
  const lock = readLockfile(project.root);
  const ids = Object.keys(lock.modules);
  if (ids.length === 0) {
    io.out(`no packages pinned — ${LOCK_FILENAME} is empty. \`despia add github:owner/repo\` pins one.`);
    return 0;
  }
  let missing = 0;
  for (const id of ids) {
    const entry = lock.modules[id]!;
    let state: string;
    try {
      materialize(id, entry, cacheDir);
      state = "resolved";
    } catch (e) {
      missing += 1;
      state = e instanceof ResolveError && e.message.includes("not in the cache")
        ? `NOT FETCHED — despia add ${id}@${entry.version}`
        : "CACHE CORRUPT — see despia add";
    }
    io.out(`${id.padEnd(34)} ${entry.version.padEnd(9)} ${(entry.scheme ?? "").padEnd(14)} ${state}` +
      (entry.crossChecked === false ? "  [never cross-checked]" : ""));
  }
  io.out(`${ids.length} package(s), ${ids.length - missing} resolved`);
  return missing > 0 ? 1 : 0;
}

/** The second module source for `despia export` (plan §6 W3): the lockfile's entries materialized
 *  out of the cache, each re-verified against its pin. Returns absolute module directories. */
export function lockedModuleDirs(projectRoot: string, cacheDir = defaultCacheDir()): Array<{ id: string; dir: string }> {
  const lock = readLockfile(projectRoot);
  return Object.entries(lock.modules)
    .filter(([id]) => id.startsWith("github:"))
    .map(([id, entry]) => ({ id, dir: materialize(id, entry, cacheDir) }));
}
