-- GENERATED by ClosedSource/scripts/prepare_server.rb — never hand-edit.
-- CLUSTER prerequisite: the three request roles every emitted policy is written against.
--
-- Run ONCE, as a SUPERUSER, before 000_dsx_schema.sql:  psql -f 000_dsx_roles.sql
-- Creating a role requires CREATEROLE, which the database owner who applies the schema
-- migration does not have — which is why this is a separate file and not a preamble.
--
-- A hosted Supabase project ALREADY HAS all three: skip this file there (running it is
-- harmless — it is idempotent — but it is not needed).
--
-- NONE OF THESE ROLES CARRIES AN ATTRIBUTE, AND THAT IS THE DESIGN. `service_role` is PLAIN
-- here, NOT `bypassrls`. Supabase's own service_role bypasses RLS cluster-wide, which reaches
-- every table in the database; the emitted policies instead name service_role on exactly the
-- tables that declared service ownership, so the reach is the declaration and nothing more.
-- It is also the portable choice — `bypassrls` needs superuser and is restricted on several
-- managed providers, while create-role plus a policy is plain SQL that behaves identically on
-- Supabase, self-hosted, RDS and Neon.
--
-- THEN GRANT MEMBERSHIP TO THE ROLE YOUR SERVER CONNECTS AS. This file cannot do it: only
-- the deploy knows that role's name. Without it every request dies on
--   permission denied to set role "authenticated"
-- which names the symptom and not the cause, so it is worth doing deliberately:
--
--   grant anon, authenticated, service_role to <the role in DSX_DATABASE_URL>;
--
-- MEMBERSHIP IS WHAT MAKES THE SERVICE PLANE WORK, and it is worth knowing why: a user-scope
-- request issues `set local role authenticated`, so a policy written `to service_role` does
-- NOT apply to it and the separation survives. A service-scope request keeps the connection
-- role, which IS a member, so the same policy DOES apply. Postgres applies a policy's TO list
-- to members of the role, so neither a role switch nor an attribute is needed on either path.
--
-- Supabase does this for you (its API connects as `authenticator`, already a member).
--
-- RESTORING A BACKUP? RUN THIS FILE FIRST. A `pg_dump` of a database carries its tables,
-- policies and GRANTS, but roles are CLUSTER objects and are never in it — measured on a real
-- dump of this schema: 0 CREATE ROLE statements, 8 GRANTs referencing these three. Restore
-- into a FRESH cluster without this file and every one of those grants fails, `pg_restore`
-- continues past the errors, and the tables come back with no privileges: every request then
-- dies on "permission denied" with the data sitting right there, intact and unreachable.
-- Restoring into the SAME cluster is fine because the roles still exist — which is exactly
-- why this is easy to miss in a drill and expensive to meet during a real recovery.
--
--   1. psql -f 000_dsx_roles.sql          (this file, as a superuser)
--   2. grant anon, authenticated, service_role to <the role in DSX_DATABASE_URL>;
--   3. pg_restore -d <database> <dump>
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin;
  end if;
end $$;
