-- GENERATED by ClosedSource/scripts/prepare_server.rb — never hand-edit.
-- The aggregate `schema` facet of every ENABLED module, compiled by the
-- Core/Server/Providers/Postgres provider (full-stack.md T3). Exclusion is the deployment
-- switch: drop a declarer and its entities vanish from this file.

-- Platform preamble. On a hosted Supabase project this changes NOTHING: the schema and
-- auth.uid() already exist and are left exactly as they are. On any other Postgres it is
-- REQUIRED — every policy below calls auth.uid(), and requests run as anon/authenticated.
create schema if not exists auth;
do $$ begin
  if not exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'auth' and p.proname = 'uid'
  ) then
    create function auth.uid() returns uuid language sql stable as $fn$
      select coalesce(
        nullif(current_setting('request.jwt.claim.sub', true), ''),
        nullif(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub', '')
      )::uuid
    $fn$;
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'anon')
  or not exists (select 1 from pg_roles where rolname = 'authenticated') then
    raise exception using
      message = 'DSX: the roles `anon` and `authenticated` do not exist',
      detail  = 'Every policy in this migration is written against them, so applying it now would create tables nothing can reach.',
      hint    = 'Run 000_dsx_roles.sql once as a superuser (creating a role needs CREATEROLE, which a database owner does not have). A hosted Supabase project already has both.';
  end if;
end $$;
grant usage on schema auth to anon, authenticated;
grant usage on schema public to anon, authenticated;

create table if not exists dsx_note (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid(),
  body text,
  pinned boolean,
  title text,
  created_at timestamptz not null default now()
);
alter table dsx_note add column if not exists body text;
alter table dsx_note add column if not exists pinned boolean;
alter table dsx_note add column if not exists title text;
create index if not exists dsx_note_pinned_idx on dsx_note (pinned);
alter table dsx_note enable row level security;
alter table dsx_note force row level security;
drop policy if exists dsx_note_owner_all on dsx_note;
create policy dsx_note_owner_all on dsx_note for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
revoke all on dsx_note from anon;
grant select, insert, update, delete on dsx_note to authenticated;

create table if not exists dsx_webhook_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid,
  payload jsonb,
  received_at timestamptz,
  source text,
  created_at timestamptz not null default now()
);
alter table dsx_webhook_events add column if not exists payload jsonb;
alter table dsx_webhook_events add column if not exists received_at timestamptz;
alter table dsx_webhook_events add column if not exists source text;
create index if not exists dsx_webhook_events_source_idx on dsx_webhook_events (source);
alter table dsx_webhook_events enable row level security;
-- service-only: RLS enabled; the ONLY policy names service_role, so no client role sees a row
drop policy if exists dsx_webhook_events_service on dsx_webhook_events;
create policy dsx_webhook_events_service on dsx_webhook_events for all to service_role using (true) with check (true);
-- NO grant: a service entity has no client route (the api-route check aborts on one),
-- and a grant would publish this table's shape into the auto-generated GraphQL schema.
revoke all on dsx_webhook_events from anon, authenticated;
grant select, insert, update, delete on dsx_webhook_events to service_role;

-- T4 queue "webhooks" — drained by POST /internal/webhooks/drain (idempotency is the UNIQUE key, enforced here, not in handler code)
create table if not exists dsx_queue_webhooks (
  id uuid primary key default gen_random_uuid(),
  enqueue_order bigint generated by default as identity,
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);
alter table dsx_queue_webhooks add column if not exists enqueue_order bigint generated by default as identity;
alter table dsx_queue_webhooks add column if not exists claimed_at timestamptz;
alter table dsx_queue_webhooks add column if not exists attempts integer not null default 0;
alter table dsx_queue_webhooks add column if not exists dead_lettered_at timestamptz;
alter table dsx_queue_webhooks add column if not exists dead_letter_reason text;
drop index if exists dsx_queue_webhooks_pending_fifo_idx;
create index if not exists dsx_queue_webhooks_pending_fifo_idx on dsx_queue_webhooks (enqueue_order) where processed_at is null and dead_lettered_at is null;
create index if not exists dsx_queue_webhooks_dead_letter_idx on dsx_queue_webhooks (dead_lettered_at desc) where dead_lettered_at is not null;
alter table dsx_queue_webhooks enable row level security;
revoke all on dsx_queue_webhooks from anon, authenticated;
grant select, insert, update, delete on dsx_queue_webhooks to service_role;
drop policy if exists dsx_queue_webhooks_service on dsx_queue_webhooks;
create policy dsx_queue_webhooks_service on dsx_queue_webhooks for all to service_role using (true) with check (true);

-- The request budget (host.ts `rate` rows). One atomic upsert per request decides the
-- count, because a select-then-update lets two concurrent requests both read the same
-- value and both write value+1 — exceeding the ceiling by exactly the traffic it exists for.
create table if not exists dsx_rate_counter (
  bucket text not null,
  window_start timestamptz not null,
  expires_at timestamptz not null,
  count integer not null default 0,
  primary key (bucket, window_start)
);
create index if not exists dsx_rate_counter_expiry_idx on dsx_rate_counter (expires_at);
alter table dsx_rate_counter enable row level security;
revoke all on dsx_rate_counter from anon, authenticated;
grant select, insert, update, delete on dsx_rate_counter to service_role;
drop policy if exists dsx_rate_counter_service on dsx_rate_counter;
create policy dsx_rate_counter_service on dsx_rate_counter for all to service_role using (true) with check (true);

-- The durable subscription feed (realtime.ts). A CURSOR over a table rather than a
-- pub/sub channel: NOTIFY delivers only to whoever is connected at that instant, so every
-- backgrounded phone silently misses events, and neither end can tell. `owner_id` being
-- nullable IS the authorization model — a row with an owner reaches that subject only.
create table if not exists dsx_event (
  seq bigint generated by default as identity primary key,
  channel text not null,
  owner_id uuid,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists dsx_event_channel_seq_idx on dsx_event (channel, seq);
create index if not exists dsx_event_created_idx on dsx_event (created_at);
alter table dsx_event enable row level security;
revoke all on dsx_event from anon, authenticated;
grant select, insert, delete on dsx_event to service_role;
drop policy if exists dsx_event_service on dsx_event;
create policy dsx_event_service on dsx_event for all to service_role using (true) with check (true);
