//
//  GENERATED by ClosedSource/scripts/prepare_server.rb — never hand-edit.
//
//  The Firebase fat-function entry: Express req/res ↔ web Request/Response
//  translation around the SAME host + generated tables every target shares.

import { onRequest } from "firebase-functions/v2/https";

import { createHost } from "../../../src/host.ts";
import { createIdentityResolver } from "../../../src/identity.ts";
import { installDataBackend, stripMountPrefix } from "../../../src/bootloader-deno.ts";
import { installEntities } from "../../../src/repo.ts";
import { assertConfigured, configuredEnv, hostOptions, type ServerConfig } from "../../../src/config.ts";
import { routes } from "../../../generated/routes.ts";
import { buildInfo } from "../../../generated/build-info.ts";
import { handlers } from "../../../generated/handlers.ts";
import { serverConfig } from "../../../generated/config.ts";
import { backendSetting, dataProviders } from "../../../generated/providers.ts";
import { installPackages } from "../../../src/packages.ts";
import { packageModules } from "../../../generated/packages.ts";
import { entities } from "../../../generated/entities.ts";

const platformEnv = (key: string): string | undefined => process.env[key];
// At MODULE LOAD, before the function serves anything: a missing required setting fails
// visibly in the Cloud Functions log instead of 401ing every caller silently (plan B4).
const declared = serverConfig as unknown as ServerConfig;
assertConfigured(declared, platformEnv);
const env = configuredEnv(declared, platformEnv);
// The SCHEMA table + the data backend boot with the function (plan B5) — same reasoning
// as the edge entry: a wrapper that skips installEntities serves handler_failed on every
// declared-CRUD route.
installEntities(entities as unknown as import("../../../src/repo.ts").EntitySpec[]);
installPackages(packageModules);
await installDataBackend(declared, backendSetting, dataProviders);
const host = createHost({
  routes: routes as unknown as import("../../../src/host.ts").ServerRoute[],
  handlers: handlers as never,
  buildInfo,
  ...hostOptions(declared),
});
const resolveIdentity = createIdentityResolver(env);

export const dsx = onRequest(async (req, res) => {
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (typeof value === "string") headers.set(key, value);
    else if (Array.isArray(value)) for (const one of value) headers.append(key, one);
  }
  const method = (req.method ?? "GET").toUpperCase();
  const raw = req.url ?? "/";
  const qi = raw.indexOf("?");
  const pathname = qi === -1 ? raw : raw.slice(0, qi);
  const search = qi === -1 ? "" : raw.slice(qi);
  const target = `https://${req.headers.host ?? "localhost"}${stripMountPrefix(pathname)}${search}`;
  const body = (req as unknown as { rawBody?: Uint8Array }).rawBody;
  const init: RequestInit = { method, headers };
  if (body !== undefined && body.length > 0 && method !== "GET" && method !== "HEAD") init.body = new Uint8Array(body);
  const webReq = new Request(target, init);
  const webRes = await host.handle(webReq, { identity: await resolveIdentity(webReq), env });
  res.status(webRes.status);
  webRes.headers.forEach((value, key) => res.setHeader(key, value));
  res.send(Buffer.from(await webRes.arrayBuffer()));
});
