-- GENERATED by ClosedSource/scripts/prepare_server.rb — never hand-edit.
-- pg_cron drains for T4 worker queues.
-- psql -v dsx_url=... -v dsx_key=... -v dsx_internal_key=... -f queue.sql
--   dsx_key          — the Supabase key that gets PAST SUPABASE'S gateway (anon or service).
--   dsx_internal_key — DSX_INTERNAL_KEY, the credential OUR host accepts for a reach:[] route.
--                      Without it the drain is a 404 and the queue never empties, silently.

create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

select cron.schedule('dsx-queue-webhooks', '* * * * *',
  format('select net.http_post(url := %L, headers := jsonb_build_object(%L, %L, %L, %L)::jsonb)',
         :'dsx_url' || '/functions/v1/dsx/internal/webhooks/drain',
         'Authorization', 'Bearer ' || :'dsx_key',
         'X-DSX-Internal-Key', :'dsx_internal_key'));

-- Retention. Expired budget windows: nothing can still be counting against them.
select cron.schedule('dsx-sweep-rate', '*/10 * * * *',
  $$delete from dsx_rate_counter where expires_at < now()$$);

-- Retention. Events past the declared history window (Core/Server config
-- `event_retention_hours`): a subscriber away longer than this resumes from the oldest
-- surviving event rather than from where it left off, which is the stated bound on the
-- "a disconnected client misses nothing" promise.
select cron.schedule('dsx-sweep-events', '17 * * * *',
  $$delete from dsx_event where created_at < now() - make_interval(hours => 24)$$);
